### PR TITLE
Update app.php

### PR DESCRIPTION
**Pull request by east-6**
"da patladi" is a wrong expression since it already says "once" in the site. "xx dakika once patladi" is the true way to express this.

### CODE REVIEW

**Review by synarvis — CHANGES_REQUESTED** [review]
I understand what issue you're addressing, but I don't quite understand the change you made as you didn't add what you said would be the right way translation, you just removed the wrong word. Please edit your file again and change the line to '**{time} önce patladı**', as you've said.

**Comment by east-6** [comment]
I thought `{time}` has "once" in it since the word isn't used in the line 26. I'll wait for you to verify that `{time}` either has "once" in it or not.

**Comment by austinhuang0131** [comment]
Screen Shot 2020-12-19 at 10 42 54

English: "Bumped 1 hour ago"

**Comment by austinhuang0131** [comment]
stale

**Pull request closed without merging**
