### PR TITLE
[FR] Translate guidelines

### PR DESCRIPTION
**Pull request by WeeskyBDW**
DISBOARD Guidelines translate in French

Ping @SmokyBird and @tai1er for checking if i haven't made mistakes (thx if you help me)

I take help of everyone

### CODE REVIEW

**Comment by WeeskyBDW** [comment]
@austinhuang0131 if you have the time

**Comment by austinhuang0131** [comment]
My French isn't that good so I'll pass

Reminder on @SmokyBird cuz he said "1h max" now it's 2

**Review by SmokyBird — COMMENTED** [review]
From what I see, here's some modifications to add:
- Add a space before colons (`:`)
- Line 18: `NSFW (contenu sexuel)`: not necessarily sexual content, it could be translated as `NSFW (pas convenable au travail)`
- Line 24: `Line could be translated as `Les serveurs enfreignants la <a href="https://discordapp.com/guidelines" target="_blank">Charte d’Utilisation de la Communauté Discord</a> sont interdits.`
- Line 27: `L'utilisation d'automates [...] est interdite.` Needs to be conjugated in the feminine, as `utilisation` is a feminine word in french
- Line 30: `contenue` should be changed to `contenu`, as the word can't be conjugated
- Line 39: Same change applies for the NSFW part (as noticed above in line 18), and correcting the sentence `doivent se déclarent` to `doivent se déclarer`
- Line 44: `Consulter aussi` could become `Consultez également`, the verb uses the imperative mood

Otherwise, all clear :)

**Comment by WeeskyBDW** [comment]
> 
> 
> From what I see, here's some modifications to add:
> 
>     * Add a space before colons (`:`)
> 
>     * Line 18: `NSFW (contenu sexuel)`: not necessarily sexual content, it could be translated as `NSFW (pas convenable au travail)`
> 
>     * Line 24: Line could be translated as `Les serveurs enfreignants la <a href="https://discordapp.com/guidelines" target="_blank">Charte d’Utilisation de la Communauté Discord</a> sont interdits.`
> 
>     * Line 27: `L'utilisation d'automates [...] est interdite.` Needs to be conjugated in the feminine, as `utilisation` is a feminine word in french
> 
>     * Line 30: `contenue` should be changed to `contenu`, as the word can't be conjugated
> 
>     * Line 39: Same change applies for the NSFW part (as noticed above in line 18), and correcting the sentence `doivent se déclarent` to `doivent se déclarer`
> 
>     * Line 44: `Consulter aussi` could become `Consultez également`, the verb uses the imperative mood
> 
> 
> Otherwise, all clear :)

Fixed, if you can recheck ^^

**Comment by SmokyBird** [comment]
It just needs the correction for line 24 (`enfreignants` instead of `violents`) and a space before the `<a>` tag and it's good :)

**Comment by WeeskyBDW** [comment]
Fixed (2)

**Comment by WeeskyBDW** [comment]
Can be merged @austinhuang0131

**Pull request merged**
