### PR TITLE
Update de.js

### PR DESCRIPTION
**Pull request by Timi25062010**
Change row 7 from "Get server page link": "Sendet die URL der Serverseite auf DISBOARD", to "Get server page link": "Sendet den Link der Serverseite auf DISBOARD",

### CODE REVIEW

**Comment by GregTCLTK** [comment]
Are there any reasons for the change? I don't see any problem with the original translation.

**Comment by Timi25062010** [comment]
> Are there any reasons for the change? I don't see any problem with the original translation.

That´s a better translation then in English it's called "link" too

**Comment by synarvis** [comment]
I agree with @GregTCLTK, it doesn't really make a difference.

**Comment by GregTCLTK** [comment]
> > Are there any reasons for the change? I don't see any problem with the original translation.
> 
> That´s a better translation then in English it's called "link" too

In English it is also called URL. So this argument doesn't really make sense.

**Comment by Timi25062010** [comment]
> > > Are there any reasons for the change? I don't see any problem with the original translation.
> > 
> > 
> > That´s a better translation then in English it's called "link" too
> 
> In English it is also called URL. So this argument doesn't really make sense.

i think link is better

**Comment by synarvis** [comment]
> > > > Are there any reasons for the change? I don't see any problem with the original translation.
> > > 
> > > 
> > > That´s a better translation then in English it's called "link" too
> > 
> > 
> > In English it is also called URL. So this argument doesn't really make sense.
> 
> i think link is better

 I mean, if you insist, I guess. But we all agree it's not really a necessary change *shrug* It's more of a nitpicking-issue as it doesn't really make a difference.

**Pull request closed without merging**
